name: OCI Instance Hunter

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          pip install oci

      - name: Executar Cacador de Instancia
        env:
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_COMPARTMENT: ${{ secrets.OCI_COMPARTMENT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          python hunter.py
